### ISSUE TITLE
[Errno 8] nodename nor servname provided, or not known"

### ISSUE THREAD

**Issue by WangQinghuCS** [wrjlewis/notion-search-alfred5-workflow#7]
In Alfred5, I come across this problem as below.
![image](https://github.com/wrjlewis/notion-search-alfred5-workflow/assets/33517563/f40df2c8-ab29-4881-a0d6-bcdbf0e08edb)

**Comment by wrjlewis** [comment]
Hey @WangQinghuCS 

This looks like your computer can't connect to notion.so, likely a DNS issue or connectivity problem. Give the error a google and see if it sheds any light on what to do, because its a fairly generic issue not linked specifically to this workflow. 

Thanks
